- name: turntouch
  mac: c2:51:f2:36:3f:ad
  buttons:
    north_press:
      type: bash
      command: echo "Hello North"
    north_double:
      type: bash
      command: echo "Double North"
    north_hold:
      type: bash
      command: echo "Hold North"
    east_press:
      type: bash
      command: echo "Hello East"
    east_double:
      type: bash
      command: echo "Double East"
    east_hold:
      type: bash
      command: echo "Hold East"
    south_press:
      type: bash
      command: echo "Hello South"
    south_double:
      type: bash
      command: echo "Double South"
    south_hold:
      type: bash
      command: echo "Hold South"
    west_press:
      type: bash
      command: echo "Hello West"
    west_double:
      type: bash
      command: echo "Double West"
    west_hold:
      type: bash
      command: echo "Hold West"
    battery_10:
      type: bash
      command: echo "Battery Low!"
